branches: 
  - "main"
  - name: "beta"
    channel: "beta"
    prerelease: true
plugins:
  - '@semantic-release/github'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: "source"
  # run prepareCmd after other steps so that changes are included in package
  - - '@semantic-release/exec'
    # See .release.sh for what files are included in release
    - prepareCmd: "sh ./.release.sh ${nextRelease.version}"
  - - '@semantic-release/git'
    - assets:
        - 'source/Runtime/AssemblyInfo.cs'
        - 'source/package.json'
        - 'CHANGELOG.md'
publish:
  - path: "@semantic-release/github" 
    assets: 
      - path: "Mirage.ClientSidePrediction.unitypackage"
        label: "Mirage.ClientSidePrediction ${nextRelease.version} Unity Package"
        name: "Mirage.ClientSidePrediction-${nextRelease.version}.unitypackage"